### ISSUE TITLE
Error in search after Spring '23 release

### ISSUE THREAD

**Issue by hrk623** [hrk623/record-hunter-sfdx#3]
When Search button is pressed, the following error message is displayed on the screen with a red toast.
Error Message: "Search: Attempt to de-reference a null object"

**Comment by VuongSyThanh** [comment]
hi bro. 
Thanks for useful and wonderful library.

Im new bie in salesforce. 
Im using your recordhunter library for practice salesforce project.
I want to ask some question for you:

1. how i can get field name of child object from parent object ?

example: I have two object are Account (parent) object and Opportunity (Child) object.

・when I want to get Account Name from Opportunity object. 
I fill: Account.Name  in input fields.

・But I want to get Opportunity Name from Account Object. 
I fill: Opportunities__r.Name, I get error message. cannot find  Opportunities__r.Name field

2. When Search button is pressed, the following error message is displayed on the screen with a red toast.
I get Error Message: "Search: Attempt to de-reference a null object"

with two question above. Could you help me some solution?
thanks you so much.

**Comment by VuongSyThanh** [comment]
@hrk623 さん
ご迷惑をおかけし申し訳ありませんでした。
よろしくお願いいたします。
